version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    allow:
      - dependency-type: "all"
    reviewers:
      - "owner"
    assign-reviewers: true
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "dependencies"
      - "automation"
    milestone: 1
    open-pull-requests-limit: 10
    rebase-strategy: "auto"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    reviewers:
      - "owner"
    assign-reviewers: true
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automation"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
